Repository digitalearthpacific/water-quality, pull requests merged in 2025-07, with the labels that each got.

#9 first thresholds completed for Navua
  coastal/drafts/.ipynb_checkpoints/navua-ndti-checkpoint.ipynb
  coastal/drafts/.ipynb_checkpoints/ndti-multiyear-stats-checkpoint.ipynb
  coastal/drafts/.ipynb_checkpoints/ndti-multiyear-stats-navua-checkpoint.ipynb
  coastal/drafts/.ipynb_checkpoints/ndti-multiyear-stats-suva-checkpoint.ipynb
  coastal/drafts/.ipynb_checkpoints/ndti_analysis_navua-checkpoint.ipynb
  coastal/drafts/.ipynb_checkpoints/ndti_analysis_navua_single-checkpoint.ipynb
  coastal/drafts/navua-ndti.ipynb
  coastal/drafts/ndti-multiyear-stats-navua.ipynb
  coastal/drafts/ndti-multiyear-stats-suva.ipynb
  coastal/drafts/ndti-multiyear-stats.ipynb
  coastal/drafts/ndti_analysis_navua.ipynb
  coastal/drafts/ndti_analysis_navua_single.ipynb
Labels: documentation, enhancement

#11 updated - coloured plot
  coastal/drafts/.ipynb_checkpoints/ndti-multiyear-stats-navua-checkpoint.ipynb
  coastal/drafts/.ipynb_checkpoints/ndti-multiyear-stats-suva-checkpoint.ipynb
  coastal/drafts/ndti-multiyear-stats-navua.ipynb
  coastal/drafts/ndti-multiyear-stats-suva.ipynb
Labels: documentation

#13 updated grids to 25km
  coastal/grids/.ipynb_checkpoints/3-coastal-25-grids-checkpoint.ipynb
  coastal/grids/3-coastal-25-grids.ipynb
Labels: documentation, enhancement, help wanted

#14 updated s2 collection
  coastal/drafts/.ipynb_checkpoints/ndti-multiyear-stats-navua-checkpoint.ipynb
  coastal/drafts/.ipynb_checkpoints/ndti-multiyear-stats-suva-checkpoint.ipynb
  coastal/drafts/__pycache__/utils.cpython-310.pyc
  coastal/drafts/ndti-multiyear-stats-navua.ipynb
  coastal/drafts/ndti-multiyear-stats-suva.ipynb
Labels: documentation, enhancement

#17 updated work on water qual
  coastal/drafts/.ipynb_checkpoints/ndti-multiyear-stats-navua-cloud-masked-checkpoint.ipynb
  coastal/drafts/ndti-multiyear-stats-navua-cloud-masked.ipynb
Labels: documentation

#28 Added Chlorophyll and update on ndti
  coastal/drafts/Chlorophyll-multiyear-stats-1.ipynb
  coastal/drafts/ndti-multiyear-stats-navua-cloud-masked.ipynb
Labels: bug, documentation

#31 Add Chlorophyll folder and updated notebooks/geojson files
  .ipynb_checkpoints/LICENSE-checkpoint
  coastal/Chlorophyll/.ipynb_checkpoints/Chlorophyll-multiyear-stats-1-checkpoint.ipynb
  coastal/Chlorophyll/Chlorophyll-multiyear-stats-1.ipynb
  coastal/Chlorophyll/Tenggano.geojson
  coastal/Chlorophyll/__pycache__/utils.cpython-310.pyc
  coastal/Chlorophyll/utils.py
Labels: documentation

#34 updated thresholds to mean
  coastal/drafts/.ipynb_checkpoints/ndti-multiyear-stats-navua-cloud-masked-checkpoint.ipynb
  coastal/drafts/ndti-multiyear-stats-navua-cloud-masked.ipynb
Labels: documentation

#35 revising cloud mask
  coastal/drafts/.ipynb_checkpoints/ndti-multiyear-stats-navua-cloud-masked-checkpoint.ipynb
  coastal/drafts/ndti-multiyear-stats-navua-cloud-masked.ipynb
Labels: documentation
